"""Lexiques 100 % hors-ligne : prénoms/noms tunisiens et villes tunisiennes.

Simple base de connaissance statique consommée par ``form_analyzer.py`` pour
corriger les lectures OCR incertaines (distance de Levenshtein) — aucune
connexion, aucun modèle à entraîner. Les listes s'élargissent manuellement
(elles sont déclaratives : on en écrit la suite, pas de retrain).
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# Prénoms tunisiens courants (liste déclarative, élargissable)
# --------------------------------------------------------------------------- #
TUNISIAN_FIRST_NAMES: frozenset[str] = frozenset(
    {
        # Masculins
        "Ahmed",
        "Mohamed",
        "Mehdi",
        "Omar",
        "Yacine",
        "Youssef",
        "Karim",
        "Walid",
        "Hedi",
        "Anis",
        "Sofiane",
        "Tarek",
        "Nabil",
        "Hatem",
        "Salim",
        "Ridha",
        "Moncef",
        "Hamdi",
        "Ayoub",
        "Rayen",
        "Mounir",
        "Fethi",
        "Hamid",
        "Khaled",
        "Sami",
        "Kamel",
        "Kais",
        "Taher",
        "Wassim",
        "Amine",
        "Marouane",
        "Nader",
        "Raouf",
        "Mourad",
        "Zied",
        "Rafik",
        "Selim",
        "Adem",
        "Aymen",
        "Brahim",
        "Chokri",
        "Dhia",
        "Emir",
        "Fadi",
        "Ghassen",
        "Houssem",
        "Ilyes",
        "Islem",
        "Jasser",
        "Lassaad",
        "Lotfi",
        "Malek",
        "Nassim",
        "Rami",
        "Skander",
        # Féminins
        "Amina",
        "Salma",
        "Rania",
        "Yasmine",
        "Nour",
        "Olfa",
        "Ines",
        "Imen",
        "Henda",
        "Marwa",
        "Asma",
        "Asya",
        "Nageh",
        "Rim",
        "Sonia",
        "Hela",
        "Zeineb",
        "Feten",
        "Abeer",
        "Besma",
        "Chaima",
        "Eya",
        "Houda",
        "Khaoula",
        "Lina",
        "Malak",
        "Mariem",
        "Wafa",
        "Meriem",
        "Omaima",
        "Rahma",
        "Salsabil",
        "Sondos",
        "Thouraya",
        "Yosra",
        "Amira",
        "Emna",
        "Fadia",
        "Ghada",
        "Hanen",
        "Jihane",
        "Khadija",
        "Nadia",
        "Ayda",
        "Farah",
        "Maya",
        "Mayssa",
        "Didi",
    }
)

# --------------------------------------------------------------------------- #
# Noms de famille tunisiens courants
# --------------------------------------------------------------------------- #
TUNISIAN_LAST_NAMES: frozenset[str] = frozenset(
    {
        "Trabelsi",
        "Ben Salah",
        "Ben Salem",
        "Ben Amor",
        "Ben Abdallah",
        "Ben Youssef",
        "Ben Ali",
        "Ben Ahmed",
        "Ben Hassine",
        "Ben Othman",
        "Ben Romdhane",
        "Ben Hadj",
        "Ben Belgacem",
        "Jaziri",
        "Gharbi",
        "Baccouche",
        "Bouslami",
        "Riahi",
        "Mansour",
        "Hammami",
        "Bouazizi",
        "Saadi",
        "Sassi",
        "Mejri",
        "Ghariani",
        "Louati",
        "Djebbi",
        "Fkih Ahmed",
        "Saidi",
        "Cherif",
        "Kadri",
        "Omrani",
        "Oueslati",
        "Ammar",
        "Rekik",
        "Belhadj",
        "Guermazi",
        "Boudebous",
        "Kallel",
        "Sellami",
        "Charfi",
        "Bousnina",
        "Marrakchi",
        "Ltaif",
        "Mhiri",
        "Abid",
        "Rassaa",
        "Zribi",
        "Dakhli",
        "Souissi",
        "Guedri",
        "Mahjoub",
        "Hammouda",
        "Jarbou",
        "Nefzaoui",
        "Toumi",
        "Sghaier",
        "Znaidi",
        "Chaabane",
        "Ghazouani",
        "Thabet",
        "Ferchichi",
        "Jerbi",
        "Kateb",
        "Naccache",
        "Ktari",
        "Klibi",
        "Msakni",
        "Soltan",
        "Ben Naceur",
        "Hassan",
        "Harbaoui",
        "Khelou",
        "Mezrigui",
        "Ghalil",
        "Boui",
        "Rahmouni",
        "Bouaziz",
        "Sfar",
        "Kaabi",
        "Daoud",
        "Fekih",
        "Hachani",
        "Jelassi",
        "Khlifi",
        "Mezghanni",
        "Naili",
        "Othmani",
        "Elloumi",
    }
)

# --------------------------------------------------------------------------- #
# Villes tunisiennes (validation « lieu de naissance »)
# --------------------------------------------------------------------------- #
TUNISIAN_CITIES: frozenset[str] = frozenset(
    {
        "Tunis",
        "Ariana",
        "La Marsa",
        "Carthage",
        "Sidi Bou Said",
        "Ben Arous",
        "Ezzahra",
        "La Goulette",
        "Radès",
        "Manouba",
        "Oued Ellil",
        "Bizerte",
        "Menzel Bourguiba",
        "Mateur",
        "Raf Raf",
        "Nabeul",
        "Hammamet",
        "Korba",
        "Soliman",
        "Grombalia",
        "Kélibia",
        "El Haouaria",
        "Sousse",
        "M'saken",
        "Hammam Sousse",
        "Enfidha",
        "Monastir",
        "Lamta",
        "Moknine",
        "Ksar Hellal",
        "Mahdia",
        "El Jem",
        "Chebba",
        "Kairouan",
        "Sbikha",
        "Sfax",
        "Skhira",
        "Kerkennah",
        "Gremda",
        "Sakiet Ezzit",
        "Gabès",
        "Médenine",
        "Ben Gardane",
        "Zarzis",
        "Houmt Souk",
        "Kébili",
        "Douz",
        "Tozeur",
        "Nefta",
        "Gafsa",
        "Metlaoui",
        "Kasserine",
        "Feriana",
        "Sidi Bouzid",
        "Siliana",
        "Le Kef",
        "Jendouba",
        "Tabarka",
        "Ain Draham",
        "Béja",
        "Zaghouan",
        "Zriba",
        "Tajerouine",
        "Thala",
        "Makthar",
        "Boussalem",
        "Fernana",
        "Hergla",
        "El Fahs",
        "Bizerte Sud",
        "El Alia",
        "Bourkis",
    }
)
